version: "1"

services:
  server-container:
    image: koboldimage
    container_name: koboldcontainer
    working_dir: /home/koboldcpp_dir
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

